# Generated by Django 6.1 on 2026-09-26 14:41

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_phase2_inbound_engine'),
        ('organization', '0002_phase1_masters'),
        ('procurement', '0002_phase1_masters'),
        ('warehouse', '0002_phase1_masters'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='incoterm',
            name='code',
            field=models.CharField(choices=[('EXW', 'Ex Works'), ('FCA', 'Free Carrier'), ('FAS', 'Free Alongside Ship'), ('FOB', 'Free On Board'), ('CFR', 'Cost and Freight'), ('CIF', 'Cost, Insurance and Freight'), ('CIP', 'Carriage and Insurance Paid To'), ('CPT', 'Carriage Paid To'), ('DAP', 'Delivered At Place'), ('DPU', 'Delivered at Place Unloaded'), ('DDP', 'Delivered Duty Paid')], max_length=3, unique=True),
        ),
        migrations.CreateModel(
            name='GateEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('gate_entry_number', models.CharField(max_length=40)),
                ('entry_at', models.DateTimeField()),
                ('purchase_reference', models.CharField(blank=True, max_length=80)),
                ('vehicle_number', models.CharField(blank=True, max_length=60)),
                ('driver_name', models.CharField(blank=True, max_length=120)),
                ('material_reference', models.CharField(blank=True, max_length=200)),
                ('quantity_note', models.CharField(blank=True, max_length=100)),
                ('document_references', models.TextField(blank=True)),
                ('remarks', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('SUBMITTED', 'Submitted'), ('LINKED_TO_GRN', 'Linked to GRN'), ('CANCELLED', 'Cancelled')], default='DRAFT', max_length=20)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='gate_entries', to='organization.company')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='gate_entries', to='procurement.supplier')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Gate entries',
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ImportShipment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('shipment_number', models.CharField(max_length=40)),
                ('named_place', models.CharField(blank=True, max_length=200)),
                ('purchase_reference', models.CharField(blank=True, max_length=80)),
                ('etd', models.DateField(blank=True, null=True)),
                ('eta', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='import_shipments', to='organization.company')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('incoterm', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='import_shipments', to='procurement.incoterm')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='import_shipments', to='procurement.supplier')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='GoodsReceiptNote',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('grn_number', models.CharField(max_length=40)),
                ('purchase_reference', models.CharField(blank=True, max_length=80)),
                ('received_at', models.DateTimeField()),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('POSTED', 'Posted'), ('CANCELLED', 'Cancelled')], default='DRAFT', max_length=20)),
                ('posted_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('domain_record_id', models.UUIDField(blank=True, null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='goods_receipts', to='organization.company')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('currency', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='organization.currency')),
                ('gate_entry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='goods_receipts', to='procurement.gateentry')),
                ('posted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('receiving_bin', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='receiving_grns', to='warehouse.bin')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='goods_receipts', to='procurement.supplier')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='goods_receipts', to='warehouse.warehouse')),
                ('shipment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='goods_receipts', to='procurement.importshipment')),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='gateentry',
            name='shipment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='gate_entries', to='procurement.importshipment'),
        ),
        migrations.CreateModel(
            name='GoodsReceiptLine',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('received_quantity', models.DecimalField(decimal_places=6, max_digits=18)),
                ('accepted_quantity', models.DecimalField(decimal_places=6, default=Decimal('0'), max_digits=18)),
                ('rejected_quantity', models.DecimalField(decimal_places=6, default=Decimal('0'), max_digits=18)),
                ('purchase_unit_cost', models.DecimalField(decimal_places=6, default=Decimal('0'), max_digits=18)),
                ('supplier_lot_number', models.CharField(blank=True, max_length=80)),
                ('lot_number', models.CharField(blank=True, max_length=80)),
                ('manufacturing_date', models.DateField(blank=True, null=True)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('line_notes', models.CharField(blank=True, max_length=255)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='inventory.item')),
                ('lot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='grn_lines', to='inventory.inventorylot')),
                ('receipt_layer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='grn_lines', to='inventory.inventoryreceiptlayer')),
                ('uom', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='inventory.unitofmeasure')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
                ('grn', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='procurement.goodsreceiptnote')),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
                'constraints': [models.CheckConstraint(condition=models.Q(('received_quantity__gte', 0)), name='ck_grnline_recv_non_neg'), models.CheckConstraint(condition=models.Q(('accepted_quantity__gte', 0)), name='ck_grnline_acc_non_neg'), models.CheckConstraint(condition=models.Q(('rejected_quantity__gte', 0)), name='ck_grnline_rej_non_neg'), models.CheckConstraint(condition=models.Q(('purchase_unit_cost__gte', 0)), name='ck_grnline_cost_non_neg')],
            },
        ),
        migrations.AddConstraint(
            model_name='importshipment',
            constraint=models.UniqueConstraint(fields=('company', 'shipment_number'), name='uq_importshipment_company_number'),
        ),
        migrations.AddConstraint(
            model_name='goodsreceiptnote',
            constraint=models.UniqueConstraint(fields=('company', 'grn_number'), name='uq_grn_company_number'),
        ),
        migrations.AddConstraint(
            model_name='gateentry',
            constraint=models.UniqueConstraint(fields=('company', 'gate_entry_number'), name='uq_gateentry_company_number'),
        ),
    ]
