# Generated by Django 6.1 on 2026-09-28 15:58

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procurement', '0005_phase3_slice_a_commercial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorder',
            name='closed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='closed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='revision_no',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='supplierbill',
            name='approved_for_ap_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='supplierbill',
            name='approved_for_ap_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='supplierbill',
            name='commercials_frozen',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='supplierbill',
            name='discount_amount',
            field=models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=18),
        ),
        migrations.AddField(
            model_name='supplierbill',
            name='discount_pct',
            field=models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=8),
        ),
        migrations.AddField(
            model_name='supplierbill',
            name='exchange_rate',
            field=models.DecimalField(decimal_places=8, default=Decimal('1'), max_digits=18),
        ),
        migrations.AlterField(
            model_name='supplierbill',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('SUBMITTED', 'Submitted'), ('APPROVED_FOR_AP', 'Approved for AP'), ('POSTED', 'Posted'), ('CANCELLED', 'Cancelled')], default='DRAFT', max_length=20),
        ),
    ]
