# Generated by Django 6.1 on 2026-09-26 14:41

import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_phase1_seed_catalog'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockLedgerEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('txn_type', models.CharField(choices=[('GRN_RECEIPT', 'GRN Receipt'), ('QC_RELEASE', 'QC Release'), ('QC_REJECT', 'QC Reject'), ('PUTAWAY', 'Putaway'), ('TRANSFER_OUT', 'Transfer Out'), ('TRANSFER_IN', 'Transfer In'), ('ADJUSTMENT_IN', 'Adjustment In'), ('ADJUSTMENT_OUT', 'Adjustment Out'), ('RESERVATION', 'Reservation'), ('RESERVATION_RELEASE', 'Reservation Release'), ('ISSUE', 'Issue'), ('ISSUE_RETURN', 'Issue Return'), ('LANDED_COST_REVALUE', 'Landed Cost Revalue')], max_length=30)),
                ('quantity_in', models.DecimalField(decimal_places=6, default=Decimal('0'), max_digits=18)),
                ('quantity_out', models.DecimalField(decimal_places=6, default=Decimal('0'), max_digits=18)),
                ('unit_cost', models.DecimalField(decimal_places=6, default=Decimal('0'), max_digits=18)),
                ('total_cost', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=18)),
                ('reference_type', models.CharField(max_length=40)),
                ('reference_id', models.UUIDField()),
                ('reason', models.CharField(blank=True, max_length=255)),
                ('occurred_at', models.DateTimeField()),
            ],
            options={
                'ordering': ['occurred_at', 'created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='StockReservation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('quantity', models.DecimalField(decimal_places=6, max_digits=18)),
                ('reference_type', models.CharField(blank=True, max_length=40)),
                ('reference_id', models.UUIDField(blank=True, null=True)),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('RELEASED', 'Released'), ('CANCELLED', 'Cancelled')], default='OPEN', max_length=20)),
                ('notes', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
    ]
