# Generated by Django 6.1 on 2026-09-26 14:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_phase2_inbound_engine'),
        ('organization', '0002_phase1_masters'),
        ('procurement', '0003_phase2_inbound_engine'),
        ('warehouse', '0002_phase1_masters'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='inventorylot',
            name='source_grn',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='lots', to='procurement.goodsreceiptnote'),
        ),
        migrations.AddField(
            model_name='landedcostdocument',
            name='posted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='landedcostdocument',
            name='posted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='landedcostdocument',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('PREVIEWED', 'Previewed'), ('POSTED', 'Posted'), ('CANCELLED', 'Cancelled')], default='DRAFT', max_length=20),
        ),
        migrations.AddField(
            model_name='stockledgerentry',
            name='bin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ledger_entries', to='warehouse.bin'),
        ),
        migrations.AddField(
            model_name='stockledgerentry',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_ledger_entries', to='organization.company'),
        ),
        migrations.AddField(
            model_name='stockledgerentry',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='stockledgerentry',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ledger_entries', to='inventory.item'),
        ),
        migrations.AddField(
            model_name='stockledgerentry',
            name='lot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ledger_entries', to='inventory.inventorylot'),
        ),
        migrations.AddField(
            model_name='stockledgerentry',
            name='receipt_layer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ledger_entries', to='inventory.inventoryreceiptlayer'),
        ),
        migrations.AddField(
            model_name='stockledgerentry',
            name='reversal_of',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reversals', to='inventory.stockledgerentry'),
        ),
        migrations.AddField(
            model_name='stockledgerentry',
            name='uom',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='inventory.unitofmeasure'),
        ),
        migrations.AddField(
            model_name='stockledgerentry',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='stockledgerentry',
            name='warehouse',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ledger_entries', to='warehouse.warehouse'),
        ),
        migrations.AddField(
            model_name='stockreservation',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_reservations', to='organization.company'),
        ),
        migrations.AddField(
            model_name='stockreservation',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='stockreservation',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reservations', to='inventory.item'),
        ),
        migrations.AddField(
            model_name='stockreservation',
            name='lot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reservations', to='inventory.inventorylot'),
        ),
        migrations.AddField(
            model_name='stockreservation',
            name='receipt_layer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reservations', to='inventory.inventoryreceiptlayer'),
        ),
        migrations.AddField(
            model_name='stockreservation',
            name='uom',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='inventory.unitofmeasure'),
        ),
        migrations.AddField(
            model_name='stockreservation',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='stockreservation',
            name='warehouse',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='warehouse.warehouse'),
        ),
        migrations.AddIndex(
            model_name='stockledgerentry',
            index=models.Index(fields=['company', 'item', 'occurred_at'], name='ix_ledger_company_item_time'),
        ),
        migrations.AddIndex(
            model_name='stockledgerentry',
            index=models.Index(fields=['reference_type', 'reference_id'], name='ix_ledger_reference'),
        ),
        migrations.AddConstraint(
            model_name='stockledgerentry',
            constraint=models.CheckConstraint(condition=models.Q(('quantity_in__gte', 0)), name='ck_ledger_qty_in_non_neg'),
        ),
        migrations.AddConstraint(
            model_name='stockledgerentry',
            constraint=models.CheckConstraint(condition=models.Q(('quantity_out__gte', 0)), name='ck_ledger_qty_out_non_neg'),
        ),
        migrations.AddConstraint(
            model_name='stockledgerentry',
            constraint=models.CheckConstraint(condition=models.Q(('quantity_in__gt', 0), ('quantity_out__gt', 0), _negated=True), name='ck_ledger_not_both_in_out'),
        ),
        migrations.AddConstraint(
            model_name='stockreservation',
            constraint=models.CheckConstraint(condition=models.Q(('quantity__gt', 0)), name='ck_reservation_qty_positive'),
        ),
    ]
