# Generated by Django 6.1 on 2026-09-26 15:49

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


def backfill_fifo_rank(apps, schema_editor):
    Layer = apps.get_model("inventory", "InventoryReceiptLayer")
    for layer in Layer.objects.all().iterator():
        if layer.fifo_rank == 0:
            layer.fifo_rank = layer.receipt_sequence
            layer.save(update_fields=["fifo_rank"])


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_phase2_inbound_engine'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='inventoryreceiptlayer',
            name='fifo_rank',
            field=models.PositiveBigIntegerField(db_index=True, default=0, help_text='FIFO ordering key; preserved across layer splits'),
        ),
        migrations.RunPython(backfill_fifo_rank, migrations.RunPython.noop),
        migrations.AddField(
            model_name='stockledgerentry',
            name='is_state_event',
            field=models.BooleanField(default=False, help_text='True for QC/reservation/valuation audit rows — not physical quantity movement.'),
        ),
        migrations.AlterField(
            model_name='inventoryreceiptlayer',
            name='receipt_sequence',
            field=models.PositiveBigIntegerField(help_text='Monotonic unique sequence within company/item'),
        ),
        migrations.AlterField(
            model_name='stockledgerentry',
            name='txn_type',
            field=models.CharField(choices=[('GRN_RECEIPT', 'GRN Receipt'), ('QC_RELEASE', 'QC Release (state event — no physical qty)'), ('QC_REJECT', 'QC Reject (state event — no physical qty)'), ('PUTAWAY', 'Putaway (legacy single entry)'), ('PUTAWAY_OUT', 'Putaway Out'), ('PUTAWAY_IN', 'Putaway In'), ('TRANSFER_OUT', 'Transfer Out'), ('TRANSFER_IN', 'Transfer In'), ('ADJUSTMENT_IN', 'Adjustment In'), ('ADJUSTMENT_OUT', 'Adjustment Out'), ('RESERVATION', 'Reservation (state event — no physical qty)'), ('RESERVATION_RELEASE', 'Reservation Release (state event)'), ('ISSUE', 'Issue'), ('ISSUE_RETURN', 'Issue Return'), ('LANDED_COST_REVALUE', 'Landed Cost Revalue (valuation event)')], max_length=30),
        ),
        migrations.CreateModel(
            name='StockReservationAllocation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('quantity', models.DecimalField(decimal_places=6, max_digits=18)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('lot', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reservation_allocations', to='inventory.inventorylot')),
                ('receipt_layer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reservation_allocations', to='inventory.inventoryreceiptlayer')),
                ('reservation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allocations', to='inventory.stockreservation')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
                'constraints': [models.CheckConstraint(condition=models.Q(('quantity__gt', 0)), name='ck_resalloc_qty_positive'), models.UniqueConstraint(fields=('reservation', 'receipt_layer'), name='uq_resalloc_reservation_layer')],
            },
        ),
    ]
