# Generated by Django 6.1 on 2026-08-25 05:21

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('entity', models.CharField(db_index=True, max_length=64)),
                ('code', models.CharField(max_length=40)),
                ('title', models.CharField(blank=True, max_length=255)),
                ('date', models.DateField()),
                ('status', models.CharField(db_index=True, default='draft', max_length=32)),
                ('fields', models.JSONField(blank=True, default=dict)),
                ('lines', models.JSONField(blank=True, default=list)),
                ('history', models.JSONField(blank=True, default=list)),
                ('links', models.JSONField(blank=True, default=list)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'production record',
                'db_table': 'production_record',
                'ordering': ['-date', '-created_at'],
                'abstract': False,
                'indexes': [models.Index(fields=['entity', 'status'], name='production__entity_9fcd45_idx'), models.Index(fields=['entity', 'date'], name='production__entity_9955cd_idx')],
                'constraints': [models.UniqueConstraint(fields=('entity', 'code'), name='production_record_entity_code')],
            },
        ),
    ]
