# Generated by Django 6.1.1 on 2026-10-07 08:15

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0007_phase3_qc_coa_required'),
        ('organization', '0002_phase1_masters'),
        ('production', '0001_initial'),
        ('warehouse', '0004_phase2_hardening_integrity'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BOM',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('code', models.CharField(max_length=60)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('ACTIVE', 'Active'), ('INACTIVE', 'Inactive')], default='DRAFT', max_length=20)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='production_boms', to='organization.company')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('output_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='production_boms', to='inventory.item')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BOMVersion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('version', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('ACTIVE', 'Active'), ('INACTIVE', 'Inactive')], default='DRAFT', max_length=20)),
                ('effective_from', models.DateField()),
                ('effective_to', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('bom', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='versions', to='production.bom')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['bom', '-version'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BOMLine',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('quantity', models.DecimalField(decimal_places=6, max_digits=18)),
                ('scrap_percent', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=8)),
                ('sequence', models.PositiveIntegerField(default=1)),
                ('component_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='production_bom_lines', to='inventory.item')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('uom', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='production_bom_lines', to='inventory.unitofmeasure')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
                ('bom_version', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lines', to='production.bomversion')),
            ],
            options={
                'ordering': ['sequence', 'created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MaterialIssue',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('document_number', models.CharField(db_index=True, editable=False, max_length=40, unique=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('issued_at', models.DateTimeField(blank=True, null=True)),
                ('posted_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('POSTED', 'Posted'), ('CANCELLED', 'Cancelled')], db_index=True, default='DRAFT', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_approved', to=settings.AUTH_USER_MODEL)),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='organization.branch')),
                ('cancelled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_cancelled', to=settings.AUTH_USER_MODEL)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='production_material_issues', to='organization.company')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='organization.department')),
                ('production_bin', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='production_material_issues', to='warehouse.bin')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='production_material_issues', to='warehouse.warehouse')),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MaterialIssueLine',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('quantity', models.DecimalField(decimal_places=6, max_digits=18)),
                ('bom_line', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='material_issue_lines', to='production.bomline')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='production_material_issue_lines', to='inventory.item')),
                ('lot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='production_material_issue_lines', to='inventory.inventorylot')),
                ('material_issue', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lines', to='production.materialissue')),
                ('receipt_layer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='production_material_issue_lines', to='inventory.inventoryreceiptlayer')),
                ('uom', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='production_material_issue_lines', to='inventory.unitofmeasure')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ProductionOrder',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('document_number', models.CharField(db_index=True, editable=False, max_length=40, unique=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('planned_quantity', models.DecimalField(decimal_places=6, max_digits=18)),
                ('produced_quantity', models.DecimalField(decimal_places=6, default=Decimal('0'), max_digits=18)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('RELEASED', 'Released'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], db_index=True, default='DRAFT', max_length=20)),
                ('planned_start', models.DateField(blank=True, null=True)),
                ('planned_end', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_approved', to=settings.AUTH_USER_MODEL)),
                ('bom_version', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='production_orders', to='production.bomversion')),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='organization.branch')),
                ('cancelled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_cancelled', to=settings.AUTH_USER_MODEL)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='production_orders', to='organization.company')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='organization.department')),
                ('output_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='production_orders', to='inventory.item')),
                ('production_bin', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='production_orders', to='warehouse.bin')),
                ('uom', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='production_orders', to='inventory.unitofmeasure')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='production_orders', to='warehouse.warehouse')),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='materialissue',
            name='production_order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='material_issues', to='production.productionorder'),
        ),
        migrations.CreateModel(
            name='ProductionOutput',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('document_number', models.CharField(db_index=True, editable=False, max_length=40, unique=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('output_date', models.DateField()),
                ('posted_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('POSTED', 'Posted'), ('CANCELLED', 'Cancelled')], db_index=True, default='DRAFT', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_approved', to=settings.AUTH_USER_MODEL)),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='organization.branch')),
                ('cancelled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_cancelled', to=settings.AUTH_USER_MODEL)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='production_outputs', to='organization.company')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='organization.department')),
                ('output_bin', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='production_outputs', to='warehouse.bin')),
                ('production_order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='outputs', to='production.productionorder')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='production_outputs', to='warehouse.warehouse')),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ProductionOutputLine',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('quantity', models.DecimalField(decimal_places=6, max_digits=18)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='production_output_lines', to='inventory.item')),
                ('lot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='production_output_lines', to='inventory.inventorylot')),
                ('production_output', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lines', to='production.productionoutput')),
                ('uom', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='production_output_lines', to='inventory.unitofmeasure')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ProductionLotTraceability',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('quantity_consumed', models.DecimalField(decimal_places=6, max_digits=18)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='production_lot_traceability', to='organization.company')),
                ('consumed_layer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='production_consumption_traceability', to='inventory.inventoryreceiptlayer')),
                ('consumed_lot', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='production_consumption_traceability', to='inventory.inventorylot')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('material_issue_line', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lot_traceability', to='production.materialissueline')),
                ('output_lot', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='production_output_traceability', to='inventory.inventorylot')),
                ('uom', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='production_traceability', to='inventory.unitofmeasure')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
                ('production_order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lot_traceability', to='production.productionorder')),
                ('output_line', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='material_traceability', to='production.productionoutputline')),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.AddIndex(
            model_name='bom',
            index=models.Index(fields=['company', 'status'], name='ix_prod_bom_company_status'),
        ),
        migrations.AddIndex(
            model_name='bom',
            index=models.Index(fields=['company', 'output_item'], name='ix_prod_bom_company_output'),
        ),
        migrations.AddConstraint(
            model_name='bom',
            constraint=models.UniqueConstraint(fields=('company', 'code'), name='uq_production_bom_company_code'),
        ),
        migrations.AddIndex(
            model_name='bomversion',
            index=models.Index(fields=['bom', 'status'], name='ix_prod_bomver_bom_status'),
        ),
        migrations.AddIndex(
            model_name='bomversion',
            index=models.Index(fields=['bom', 'effective_from'], name='ix_prod_bomver_effective'),
        ),
        migrations.AddConstraint(
            model_name='bomversion',
            constraint=models.UniqueConstraint(fields=('bom', 'version'), name='uq_production_bom_version'),
        ),
        migrations.AddConstraint(
            model_name='bomversion',
            constraint=models.CheckConstraint(condition=models.Q(('version__gte', 1)), name='ck_production_bom_version_positive'),
        ),
        migrations.AddIndex(
            model_name='bomline',
            index=models.Index(fields=['bom_version', 'component_item'], name='ix_prod_bomline_component'),
        ),
        migrations.AddConstraint(
            model_name='bomline',
            constraint=models.UniqueConstraint(fields=('bom_version', 'sequence'), name='uq_production_bomline_sequence'),
        ),
        migrations.AddConstraint(
            model_name='bomline',
            constraint=models.CheckConstraint(condition=models.Q(('quantity__gt', 0)), name='ck_production_bomline_qty_positive'),
        ),
        migrations.AddConstraint(
            model_name='bomline',
            constraint=models.CheckConstraint(condition=models.Q(('scrap_percent__gte', 0)), name='ck_production_bomline_scrap_non_neg'),
        ),
        migrations.AddIndex(
            model_name='materialissueline',
            index=models.Index(fields=['material_issue', 'item'], name='ix_prod_miline_issue_item'),
        ),
        migrations.AddIndex(
            model_name='materialissueline',
            index=models.Index(fields=['lot'], name='ix_prod_miline_lot'),
        ),
        migrations.AddIndex(
            model_name='materialissueline',
            index=models.Index(fields=['receipt_layer'], name='ix_prod_miline_layer'),
        ),
        migrations.AddConstraint(
            model_name='materialissueline',
            constraint=models.CheckConstraint(condition=models.Q(('quantity__gt', 0)), name='ck_prod_miline_qty_positive'),
        ),
        migrations.AddIndex(
            model_name='productionorder',
            index=models.Index(fields=['company', 'status'], name='ix_prod_order_company_status'),
        ),
        migrations.AddIndex(
            model_name='productionorder',
            index=models.Index(fields=['company', 'output_item'], name='ix_prod_order_output_item'),
        ),
        migrations.AddIndex(
            model_name='productionorder',
            index=models.Index(fields=['company', 'warehouse', 'status'], name='ix_prod_order_wh_status'),
        ),
        migrations.AddConstraint(
            model_name='productionorder',
            constraint=models.CheckConstraint(condition=models.Q(('planned_quantity__gt', 0)), name='ck_prod_order_planned_qty_positive'),
        ),
        migrations.AddConstraint(
            model_name='productionorder',
            constraint=models.CheckConstraint(condition=models.Q(('produced_quantity__gte', 0)), name='ck_prod_order_produced_qty_non_neg'),
        ),
        migrations.AddConstraint(
            model_name='productionorder',
            constraint=models.CheckConstraint(condition=models.Q(('produced_quantity__lte', models.F('planned_quantity'))), name='ck_prod_order_produced_lte_planned'),
        ),
        migrations.AddIndex(
            model_name='materialissue',
            index=models.Index(fields=['company', 'status'], name='ix_prod_mi_company_status'),
        ),
        migrations.AddIndex(
            model_name='materialissue',
            index=models.Index(fields=['company', 'production_order'], name='ix_prod_mi_company_order'),
        ),
        migrations.AddIndex(
            model_name='productionoutput',
            index=models.Index(fields=['company', 'status'], name='ix_prod_output_company_status'),
        ),
        migrations.AddIndex(
            model_name='productionoutput',
            index=models.Index(fields=['company', 'production_order'], name='ix_prod_output_company_order'),
        ),
        migrations.AddIndex(
            model_name='productionoutputline',
            index=models.Index(fields=['production_output', 'item'], name='ix_prod_outline_output_item'),
        ),
        migrations.AddIndex(
            model_name='productionoutputline',
            index=models.Index(fields=['lot'], name='ix_prod_outline_lot'),
        ),
        migrations.AddConstraint(
            model_name='productionoutputline',
            constraint=models.CheckConstraint(condition=models.Q(('quantity__gt', 0)), name='ck_prod_outputline_qty_positive'),
        ),
        migrations.AddIndex(
            model_name='productionlottraceability',
            index=models.Index(fields=['company', 'production_order'], name='ix_prod_trace_company_order'),
        ),
        migrations.AddIndex(
            model_name='productionlottraceability',
            index=models.Index(fields=['consumed_lot'], name='ix_prod_trace_consumed_lot'),
        ),
        migrations.AddIndex(
            model_name='productionlottraceability',
            index=models.Index(fields=['output_lot'], name='ix_prod_trace_output_lot'),
        ),
        migrations.AddConstraint(
            model_name='productionlottraceability',
            constraint=models.CheckConstraint(condition=models.Q(('quantity_consumed__gt', 0)), name='ck_prod_trace_qty_positive'),
        ),
    ]
