# Generated by Django 6.1 on 2026-09-26 14:41

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_phase2_inbound_engine'),
        ('organization', '0002_phase1_masters'),
        ('procurement', '0003_phase2_inbound_engine'),
        ('quality', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='QCInspection',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('inspection_number', models.CharField(max_length=40)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('PASSED', 'Passed'), ('FAILED', 'Failed')], default='DRAFT', max_length=20)),
                ('fail_disposition', models.CharField(blank=True, choices=[('QUARANTINED', 'Quarantined'), ('REJECTED', 'Rejected')], max_length=20)),
                ('inspected_at', models.DateTimeField(blank=True, null=True)),
                ('remarks', models.TextField(blank=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='qc_inspections', to='organization.company')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('grn', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='qc_inspections', to='procurement.goodsreceiptnote')),
                ('inspected_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='inventory.item')),
                ('lot', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='qc_inspections', to='inventory.inventorylot')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
                'constraints': [models.UniqueConstraint(fields=('company', 'inspection_number'), name='uq_qcinspection_company_number')],
            },
        ),
    ]
