# Generated by Django 6.1 on 2026-09-26 15:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_phase2_hardening_integrity'),
        ('warehouse', '0003_phase2_inbound_engine'),
    ]

    operations = [
        migrations.AddField(
            model_name='cyclecountline',
            name='receipt_layer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cycle_count_lines', to='inventory.inventoryreceiptlayer'),
        ),
        migrations.AddField(
            model_name='stockadjustment',
            name='receipt_layer',
            field=models.ForeignKey(blank=True, help_text='Required for layer-level adjustments; never silently pick first layer', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='adjustments', to='inventory.inventoryreceiptlayer'),
        ),
    ]
