# Generated by Django 6.1 on 2026-08-15 13:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organization', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentNumberSequence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prefix', models.CharField(max_length=10)),
                ('last_number', models.PositiveBigIntegerField(default=0)),
                ('padding', models.PositiveSmallIntegerField(default=6)),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='organization.branch')),
                ('fiscal_year', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='organization.fiscalyear')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('prefix', 'fiscal_year', 'branch'), name='uq_docnumseq_prefix_fy_branch')],
            },
        ),
    ]
