import { Download, Printer, FileText, Search } from "lucide-react";
import { toast } from "sonner";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { downloadCsv, type CsvRow } from "@/lib/export";

export const PERIODS = [
  { id: "7d", label: "Last 7 days" },
  { id: "30d", label: "Last 30 days" },
  { id: "quarter", label: "This quarter" },
  { id: "year", label: "Fiscal year 2081/82" },
] as const;

export type PeriodId = (typeof PERIODS)[number]["id"];

interface Props {
  query: string;
  onQuery: (v: string) => void;
  placeholder?: string;
  period: PeriodId;
  onPeriod: (v: PeriodId) => void;
  extra?: React.ReactNode;
  filename: string;
  rows: CsvRow[];
}

export function ReportToolbar({ query, onQuery, placeholder, period, onPeriod, extra, filename, rows }: Props) {
  return (
    <div className="flex flex-col gap-3 lg:flex-row lg:items-center">
      <div className="relative flex-1">
        <Search className="pointer-events-none absolute left-3 top-1/2 h-4 w-4 -translate-y-1/2 text-muted-foreground" />
        <Input value={query} onChange={(e) => onQuery(e.target.value)} placeholder={placeholder ?? "Search..."} className="pl-9" />
      </div>
      <div className="flex flex-wrap gap-2">
        <Select value={period} onValueChange={(v) => onPeriod(v as PeriodId)}>
          <SelectTrigger className="w-full min-w-40 sm:w-44"><SelectValue /></SelectTrigger>
          <SelectContent>
            {PERIODS.map((p) => (<SelectItem key={p.id} value={p.id}>{p.label}</SelectItem>))}
          </SelectContent>
        </Select>
        {extra}
      </div>
      <div className="flex gap-2 print:hidden">
        <Button variant="outline" size="sm" className="flex-1 gap-2 lg:flex-none" onClick={() => { downloadCsv(filename, rows); toast.success("Excel/CSV exported"); }}>
          <Download className="h-4 w-4" /> Excel
        </Button>
        <Button variant="outline" size="sm" className="flex-1 gap-2 lg:flex-none" onClick={() => toast.info("PDF export will be generated by the backend")}>
          <FileText className="h-4 w-4" /> PDF
        </Button>
        <Button variant="outline" size="sm" className="flex-1 gap-2 lg:flex-none" onClick={() => window.print()}>
          <Printer className="h-4 w-4" /> Print
        </Button>
      </div>
    </div>
  );
}
