# Generated by Django 6.1 on 2026-09-28 15:58

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0002_phase3_slice_a_commercial'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesinvoice',
            name='commercials_frozen',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='salesinvoice',
            name='exchange_rate',
            field=models.DecimalField(decimal_places=8, default=Decimal('1'), max_digits=18),
        ),
        migrations.AddField(
            model_name='salesorder',
            name='pack_status',
            field=models.CharField(choices=[('NOT_STARTED', 'Not Started'), ('DONE', 'Done')], default='NOT_STARTED', max_length=20),
        ),
        migrations.AddField(
            model_name='salesorder',
            name='pick_status',
            field=models.CharField(choices=[('NOT_STARTED', 'Not Started'), ('DONE', 'Done')], default='NOT_STARTED', max_length=20),
        ),
        migrations.AddField(
            model_name='salesorder',
            name='promised_delivery_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='salesorderline',
            name='cancelled_quantity',
            field=models.DecimalField(decimal_places=6, default=Decimal('0'), max_digits=18),
        ),
    ]
